<?php
global $dummydata;
$dummydata = new stdClass();
$dummydata->sessions =  array(
    0 =>
    array(
      'id' => '9',
      'facetofaceid' => '9',
      'name' => 'Fitting Feedback',
      'courseid' => '47',
      'location' => 'Teams',
      'room' => 'Teams',
      'venue' => 'NA',
      'sessionid' => NULL,
      'timestart' => '1655766000',
      'timefinish' => '1655771400',
      'duration' => '90',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '21-06-2022',
      'time' => '09:00',
    ),
    1 =>
    array(
      'id' => '10',
      'facetofaceid' => '10',
      'name' => 'Time Management',
      'courseid' => '51',
      'location' => 'Teams',
      'room' => 'Teams',
      'venue' => 'NA',
      'sessionid' => NULL,
      'timestart' => '1655953200',
      'timefinish' => '1655956800',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '23-06-2022',
      'time' => '01:00',
    ),
    2 =>
    array(
      'id' => '11',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Kilsyth',
      'room' => NULL,
      'venue' => 'MR 11',
      'sessionid' => NULL,
      'timestart' => '1654228800',
      'timefinish' => '1654232400',
      'duration' => '0',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '03-06-2022',
      'time' => '02:00',
    ),
    3 =>
    array(
      'id' => '12',
      'facetofaceid' => '12',
      'name' => 'ARB Online Intermediate Training Session',
      'courseid' => '64',
      'location' => 'Teams',
      'room' => 'Virtual',
      'venue' => 'Virtual',
      'sessionid' => NULL,
      'timestart' => '1658365200',
      'timefinish' => '1658368800',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '21-07-2022',
      'time' => '11:00',
    ),
    4 =>
    array(
      'id' => '13',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Brendale, QLD',
      'room' => 'Brendale DC',
      'venue' => 'MR 1',
      'sessionid' => NULL,
      'timestart' => '1656302400',
      'timefinish' => '1656313200',
      'duration' => '120',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '27-06-2022',
      'time' => '02:00',
    ),
    5 =>
    array(
      'id' => '14',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Brendale DC',
      'venue' => 'Conference Room',
      'sessionid' => NULL,
      'timestart' => '1656457200',
      'timefinish' => '1656460800',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '29-06-2022',
      'time' => '09:00',
    ),
    6 =>
    array(
      'id' => '15',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Brendale DC',
      'venue' => 'Conference Room',
      'sessionid' => NULL,
      'timestart' => '1656464400',
      'timefinish' => '1656468000',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '29-06-2022',
      'time' => '11:00',
    ),
    7 =>
    array(
      'id' => '16',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Brendale DC',
      'venue' => 'Conference Room',
      'sessionid' => NULL,
      'timestart' => '1656471600',
      'timefinish' => '1656475200',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '29-06-2022',
      'time' => '01:00',
    ),
    8 =>
    array(
      'id' => '17',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Nundah',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1656543600',
      'timefinish' => '1656547200',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '30-06-2022',
      'time' => '09:00',
    ),
    9 =>
    array(
      'id' => '18',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Nundah',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1656550800',
      'timefinish' => '1656554400',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '30-06-2022',
      'time' => '11:00',
    ),
    10 =>
    array(
      'id' => '19',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Nundah',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1656558000',
      'timefinish' => '1656561600',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '30-06-2022',
      'time' => '01:00',
    ),
    11 =>
    array(
      'id' => '20',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Canningvale DC',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655074800',
      'timefinish' => '1655078400',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '13-06-2022',
      'time' => '09:00',
    ),
    12 =>
    array(
      'id' => '21',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Canningvale DC',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655157600',
      'timefinish' => '1655161200',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '14-06-2022',
      'time' => '08:00',
    ),
    13 =>
    array(
      'id' => '22',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Canningvale DC',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655164800',
      'timefinish' => '1655168400',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '14-06-2022',
      'time' => '10:00',
    ),
    14 =>
    array(
      'id' => '23',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Canningvale DC',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655172000',
      'timefinish' => '1655175600',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '14-06-2022',
      'time' => '12:00',
    ),
    15 =>
    array(
      'id' => '24',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Wangara',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655179200',
      'timefinish' => '1655182800',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '14-06-2022',
      'time' => '02:00',
    ),
    16 =>
    array(
      'id' => '25',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Wangara',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655182800',
      'timefinish' => '1655186400',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '14-06-2022',
      'time' => '03:00',
    ),
    17 =>
    array(
      'id' => '26',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Osborne Park',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655247600',
      'timefinish' => '1655251200',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '15-06-2022',
      'time' => '09:00',
    ),
    18 =>
    array(
      'id' => '27',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Mandurah',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655330400',
      'timefinish' => '1655334000',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '16-06-2022',
      'time' => '08:00',
    ),
    19 =>
    array(
      'id' => '28',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Canningvale',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655344800',
      'timefinish' => '1655348400',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '16-06-2022',
      'time' => '12:00',
    ),
    20 =>
    array(
      'id' => '29',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Western Australia',
      'room' => 'Welshpool',
      'venue' => 'Training Room',
      'sessionid' => NULL,
      'timestart' => '1655420400',
      'timefinish' => '1655424000',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '17-06-2022',
      'time' => '09:00',
    ),
    21 =>
    array(
      'id' => '30',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Teams',
      'venue' => 'Teams',
      'sessionid' => NULL,
      'timestart' => '1658300400',
      'timefinish' => '1658304000',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '20-07-2022',
      'time' => '05:00',
    ),
    22 =>
    array(
      'id' => '31',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Queensland',
      'room' => 'Teams',
      'venue' => 'Teams',
      'sessionid' => NULL,
      'timestart' => '1658386800',
      'timefinish' => '1658390400',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '21-07-2022',
      'time' => '05:00',
    ),
    23 =>
    array(
      'id' => '32',
      'facetofaceid' => '11',
      'name' => 'Appropriate Workplace Behaviours',
      'courseid' => '52',
      'location' => 'Kilsyth',
      'room' => 'Room 11',
      'venue' => 'Room 11',
      'sessionid' => NULL,
      'timestart' => '1659049200',
      'timefinish' => '1659052800',
      'duration' => '60',
      'userid' => NULL,
      'statuscode' => NULL,
      'date' => '29-07-2022',
      'time' => '09:00',
    ),
  );
